apiVersion: v1
kind: Service
metadata:
  name: code-talk-client
  namespace: default
  labels:
    app: code-talk
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: code-talk
    component: client
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: code-talk-server
  namespace: default
  labels:
    app: code-talk
    component: server
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: code-talk
    component: server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
