apiVersion: v1
kind: Service
metadata:
  name: educationelly-graphql-client
  namespace: default
  labels:
    app: educationelly-graphql
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: educationelly-graphql
    component: client
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: educationelly-graphql-server
  namespace: default
  labels:
    app: educationelly-graphql
    component: server
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: educationelly-graphql
    component: server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
