apiVersion: v1
kind: Service
metadata:
  name: educationelly-client
  namespace: default
  labels:
    app: educationelly
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: educationelly
    component: client
  ports:
  - name: http
    port: 3000
    targetPort: 5000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: educationelly-server
  namespace: default
  labels:
    app: educationelly
    component: server
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: educationelly
    component: server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
