apiVersion: v1
kind: Service
metadata:
  name: intervalai-client
  namespace: default
  labels:
    app: intervalai
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: intervalai
    component: client
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: intervalai-server
  namespace: default
  labels:
    app: intervalai
    component: server
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: intervalai
    component: server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
